name: Run System Tests

on:
  push:
    branches: [ "master", "feature/ci-actions" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  run-tests:
    if: ${{ github.event_name == 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install Python Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.12 python3-pip
          pip install -r requirements.txt

      - name: Run Tests
        id: run-tests
        run: |
          pytest || exit 1
          echo "run-tests-success=true" >> $GITHUB_OUTPUT

      - name: Check Results Directory
        run: ls -lah ./allure-results

      - name: Install Allure
        run: |
          npm install -g allure-commandline
      - name: Generate Allure Report
        run: |
          allure generate ./allure-results --clean -o ./allure-report
          echo "Allure Report generated successfully."
          ls -lah ./allure-report

      - name: Save Allure Report Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: ./allure-report

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: ./allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history