name: Run System Tests

on:
  push:
    branches: [ "master", "feature/ci-actions" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  run-tests:
    if: ${{ github.event_name == 'workflow_dispatch'}}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Install Python Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3.12 python3-pip
          pip install -r requirements.txt

      - name: Run Tests
        id: run-tests
        run: pytest
        continue-on-error: true

      - name: Install Allure
        run: npm install -g allure-commandline

      - name: Generate Allure Report
        run: |
          allure generate ./allure-results --clean -o ./allure-report
          echo "Allure Report generated successfully."
          ls -lah ./allure-report

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: ./allure-report

      - name: Checkout gh-pages
        if: always()
        uses: actions/checkout@v3
        with:
          ref: gh-pages
          path: gh-pages

      - name: Publish Report
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./allure-report
          destination_dir: ./latest-report