name: Docker Image CI with Allure Report

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag petstore_tests_image:latest

      - name: Run tests and get results
        continue-on-error: true  # Продолжаем даже если тесты упали
        run: |
          # Создаём директорию для результатов
          mkdir -p ./allure-results
          # Запускаем контейнер с автоматическим удалением после выполнения
          docker run --rm \
            -v $(pwd)/allure-results:/app/allure-results \
            petstore_tests_image:latest

      - name: Generate Allure report
        if: always()  # Выполняем всегда, даже если тесты упали
        run: |
          # Устанавливаем Allure CLI
          sudo apt-get update
          sudo apt-get install -y allure
          # Генерируем отчёт
          allure generate --clean ./allure-results -o ./allure-report

      - name: Upload artifact for deployment
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./allure-report

  deploy:
    needs: build-and-test
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        if: always()
        uses: actions/deploy-pages@v4