#name: Docker Image CI with Allure Report
#
#on:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]
#
#jobs:
#  build-and-test:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Build the Docker image
#        run: docker build . --file Dockerfile --tag petstore_tests_image:latest
#
#      - name: Prepare results directory
#        run: |
#          mkdir -p ./allure-results
#          chmod 777 ./allure-results  # Даём полные права на директорию
#
#      - name: Run tests
#        continue-on-error: true
#        run: |
#          docker run --rm \
#            -v $(pwd)/allure-results:/app/allure-results \
#            petstore_tests_image:latest
#
#      - name: Generate Allure report
#        if: always()
#        run: |
#          sudo apt-get update
#          sudo apt-get install -y allure
#          allure generate --clean ./allure-results -o ./allure-report
#
#      - name: Upload artifact
#        if: always()
#        uses: actions/upload-pages-artifact@v3
#        with:
#          path: ./allure-report
#
#  deploy:
#    needs: build-and-test
#    permissions:
#      pages: write
#      id-token: write
#    environment:
#      name: github-pages
#      url: ${{ steps.deployment.outputs.page_url }}
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Deploy to GitHub Pages
#        id: deployment
#        if: always()
#        uses: actions/deploy-pages@v4